FROM nginx
MAINTAINER Aggelos Avgerinos <evaggelos.avgerinos@gmail.com>

RUN rm -rf /usr/share/nginx/html
COPY public /usr/share/nginx/html
COPY config/deploy/nginx.conf /etc/nginx/conf.d/default.conf
